USE [QuanLyQuanCaphe]
GO

/****** Object:  Database [QuanLyQuanCaphe]    Script Date: 8/3/2022 8:01:57 AM ******/
CREATE DATABASE [QuanLyQuanCaphe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyQuanCaphe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyQuanCaphe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyQuanCaphe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyQuanCaphe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyQuanCaphe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyQuanCaphe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyQuanCaphe] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLyQuanCaphe] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLyQuanCaphe] SET  READ_WRITE 
GO


